[package]
name = "task-rp235x-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = { path = "../../sys/userlib" }
task-rp235x-usb-api = { path = "../rp235x-usb-api" }
drv-rp235x-gpio-api = { path = "../../drv/rp235x-gpio-api" }
drv-rp235x-uart-api = { path = "../../drv/rp235x-uart-api" }
drv-rp235x-spi-api = { path = "../../drv/rp235x-spi-api" }
drv-rp235x-i2c-api = { path = "../../drv/rp235x-i2c-api" }
drv-rp235x-flash-api = { path = "../../drv/rp235x-flash-api" }
drv-rp235x-mailbox-api = { path = "../../drv/rp235x-mailbox-api", optional = true }
drv-rp235x-adc-api = { path = "../../drv/rp235x-adc-api" }
drv-rp235x-pwm-api = { path = "../../drv/rp235x-pwm-api" }
drv-rp235x-cyw43-api = { path = "../../drv/rp235x-cyw43-api", optional = true }
drv-rp235x-slink-api = { path = "../../drv/rp235x-slink-api", optional = true }
drv-rp235x-ws2812-api = { path = "../../drv/rp235x-ws2812-api", optional = true }

[features]
cyw43 = ["dep:drv-rp235x-cyw43-api"]
mailbox = ["dep:drv-rp235x-mailbox-api"]
slink = ["dep:drv-rp235x-slink-api"]
ws2812 = ["dep:drv-rp235x-ws2812-api"]

[[bin]]
name = "task-rp235x-shell"
test = false
doctest = false
bench = false

[lints]
workspace = true
