[package]
name = "task-rp235x-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = { path = "../../sys/userlib" }
task-rp235x-usb-api = { path = "../rp235x-usb-api" }
drv-rp235x-gpio-api = { path = "../../drv/rp235x-gpio-api" }
drv-rp235x-uart-api = { path = "../../drv/rp235x-uart-api" }
drv-rp235x-spi-api = { path = "../../drv/rp235x-spi-api" }
drv-rp235x-i2c-api = { path = "../../drv/rp235x-i2c-api" }

[[bin]]
name = "task-rp235x-shell"
test = false
doctest = false
bench = false

[lints]
workspace = true
