// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! QSPI flash driver server for the RP2350 (RP235x) -- stage 1.
//!
//! Serves flash *reads* (safe while XIP is live: the driver just copies from
//! the memory-mapped XIP window) and boot-ROM table lookups, over the Idol
//! interface in `idl/rp235x-flash.idol`.
//!
//! Runs unprivileged with no peripherals; instead it gets two `extern-regions`
//! from `memory-pico-2.toml`:
//! * `rom` (0x20..0x8000, r-x) -- read the ROM lookup table (and later, call
//!   the ROM flash functions). Starts at 0x20, not 0, to avoid overlapping
//!   the kernel's per-task null region (see the memory toml);
//! * `xip` (0x14000000 uncached mirror, r--) -- read any flash address.
//!
//! Erase/program are NOT here yet. They require (datasheet sec 5.4.8.9):
//! the kernel text + vector table RAM-resident (XIP fetches bus-error while
//! the QMI is in direct mode, and SysTick fires every ms), ACCESSCTRL opened
//! for QMI (Secure-Privileged-only by default; the ROM flash code runs at the
//! caller's privilege), and a RAM-resident wrapper for the multi-call
//! exit-XIP/op/restore sequence. That is stage 2.

#![no_std]
#![no_main]

use drv_rp235x_flash_api::FlashError;
use idol_runtime::{Leased, LenLimit, RequestError, W};
use userlib::RecvMessage;

// XIP_BASE (the uncached XIP mirror, XIP_NOCACHE_NOALLOC_BASE -- the cached
// window at 0x10000000 would overlap this task's own code region, which
// PMSAv8 prohibits) and FLASH_SIZE, generated by build.rs from this task's
// `xip` extern region so they track the board's memory config.
include!(concat!(env!("OUT_DIR"), "/flash_config.rs"));

struct ServerImpl;

impl idl::InOrderRp235xFlashImpl for ServerImpl {
    fn read(
        &mut self,
        _: &RecvMessage,
        offset: u32,
        dest: LenLimit<Leased<W, [u8]>, 256>,
    ) -> Result<usize, RequestError<FlashError>> {
        if offset >= FLASH_SIZE {
            return Err(FlashError::BadAddress.into());
        }
        // Short read at the end of the device: return what fits.
        let len = dest.len().min((FLASH_SIZE - offset) as usize);
        let mut buf = [0u8; 256];
        // SAFETY: the range is inside the `xip` extern region granted to this
        // task, and reads from live XIP are side-effect free.
        unsafe {
            core::ptr::copy_nonoverlapping(
                (XIP_BASE + offset) as *const u8,
                buf.as_mut_ptr(),
                len,
            );
        }
        dest.write_range(0..len, &buf[..len])
            .map_err(|_| RequestError::went_away())?;
        Ok(len)
    }

    fn rom_lookup(
        &mut self,
        _: &RecvMessage,
        code: u16,
    ) -> Result<u32, RequestError<core::convert::Infallible>> {
        // Match Secure-Arm functions and data entries, so the shell can probe
        // both kinds. (An entry never carries both flags, per the bootrom.)
        Ok(rp235x_romapi::rom_table_lookup(
            code.to_le_bytes(),
            rp235x_romapi::RT_FLAG_FUNC_ARM_SEC | rp235x_romapi::RT_FLAG_DATA,
        ) as u32)
    }

    fn reboot(
        &mut self,
        _: &RecvMessage,
        bootsel: u8,
    ) -> Result<u32, RequestError<core::convert::Infallible>> {
        if bootsel != 0 {
            // Rebooting into BOOTSEL means calling the ROM's reboot function,
            // and calling *any* ROM function from an unprivileged task
            // currently faults (the ROM enters via RCP-canary instructions;
            // investigation parked until a debug probe is available). Report
            // unsupported instead of wedging the system.
            return Ok(u32::MAX);
        }
        // Plain reboot, no ROM involved: select everything but the processor
        // cold domain for watchdog reset, clear any stale vectored-boot magic
        // in the scratch registers, and force the reset. Needs the
        // watchdog + psm MPU grants (app.toml) and ACCESSCTRL opened for them
        // (rp235x-startup).
        let psm = unsafe { &*rp235x_pac::PSM::ptr() };
        let wd = unsafe { &*rp235x_pac::WATCHDOG::ptr() };
        psm.wdsel().write(|w| unsafe { w.bits(0xffff_fffe) });
        wd.scratch4().write(|w| unsafe { w.bits(0) });
        wd.ctrl().modify(|_, w| w.trigger().set_bit());
        // Reset is effectively immediate; this reply is best-effort.
        Ok(0)
    }
}

impl idol_runtime::NotificationHandler for ServerImpl {
    fn current_notification_mask(&self) -> u32 {
        0
    }
    fn handle_notification(&mut self, _bits: userlib::NotificationBits) {}
}

#[export_name = "main"]
fn main() -> ! {
    let mut server = ServerImpl;
    let mut incoming = [0u8; idl::INCOMING_SIZE];
    loop {
        idol_runtime::dispatch(&mut incoming, &mut server);
    }
}

mod idl {
    use drv_rp235x_flash_api::FlashError;
    include!(concat!(env!("OUT_DIR"), "/server_stub.rs"));
}
